# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: false
  collapse_walkthrough: false
  path_filters:
    - "!basilisk/res/**"
  path_instructions:
    - path: "**/*.py"
      instructions: |
        ## Indentation
        We use tabs, not spaces.
        ## naming conventions
        - **snake_case** for variables and functions
        - **PascalCase** for classes
        - **UPPER_SNAKE_CASE** for constants
        - **snake_case** for files and directories
        - Use **whole words** in names when possible
        ## documentation
        - Use **docstrings** for all public classes and functions
        - Use **type hints** for all public classes and functions
        - Use **google style** for docstrings
        ## Strings
        - Preserve existing quote style; prefer double quotes for new code
        - Use **\_("string")** for translatable strings
        - Use **# Translators:** comment (capital T) before translatable strings to provide context for translators
        ## Imports
        - Use **from __future__ import annotations** in all presenter and service modules
        - Group imports: standard library → third-party → local (basilisk), alphabetically sorted
        ## MVP Architecture
        - **Views** live in `basilisk/views/` (wxPython UI, no business logic)
        - **Presenters** live in `basilisk/presenters/` (business logic, no wx imports where possible)
        - **Services** live in `basilisk/services/` (reusable logic, thread-safe async operations)
        - Presenters receive a view via injection; do not access wx directly in presenters
        - Use `DestroyGuardMixin` + `@_guard_destroying` for presenter callbacks that may fire after view destruction
        - Use `ErrorDisplayMixin` on views; call `view.show_error()` / `view.show_enhanced_error()` from presenters

  tools:
    github-checks:
      enabled: true
    languagetool:
      enabled: true
    markdownlint:
      enabled: true
    pylint:
      enabled: false
    ruff:
      enabled: true
    yamllint:
      enabled: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "chore(deps):"
      - "chore(deps-dev):"
      - "ci(deps):"
    drafts: false
    base_branches:
      - master
chat:
  auto_reply: true
