# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: false
  collapse_walkthrough: false
  path_filters:
    - "!basilisk/res/**"
  path_instructions:
    - path: "**/*.py"
      instructions: |
        ## Indentation
        We use tabs, not spaces.
        ## naming conventions
        - **snake_case** for variables and functions
        - **PascalCase** for classes
        - **UPPER_SNAKE_CASE** for constants
        - **snake_case** for files and directories
        - Use **whole words** in names when possible
        ## documentation
        - Use **docstrings** for all public classes and functions
        - Use **type hints** for all public classes and functions
        - Use **google style** for docstrings
        ## Strings
        - Always use **double quotes** for strings
        - Use **percent formatting** for string
        - Use **\_("string")** for translatable strings
        - Use \*\*# translator: \*\* with context for translatable strings

  tools:
    github-checks:
      enabled: true
    languagetool:
      enabled: true
    markdownlint:
      enabled: true
    pylint:
      enabled: false
    ruff:
      enabled: true
    yamllint:
      enabled: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "chore(deps):"
      - "chore(deps-dev):"
      - "ci(deps):"
    drafts: false
    base_branches:
      - master
chat:
  auto_reply: true
