src = ["src"]
respect-gitignore = true
line-length = 120
unsafe-fixes = false
target-version = "py312"
[format]
indent-style = "tab"
line-ending = "lf"
quote-style = "preserve"
skip-magic-trailing-comma = true
[lint]
ignore-init-module-imports = true
