def _(message: str) -> str: ...
def gettext(message: str) -> str: ...
def ngettext(singular: str, plural: str, n: int) -> str: ...
def pgettext(context: str, message: str) -> str: ...
def npgettext(context: str, singular: str, plural: str, n: int) -> str: ...
