api_token_env: CROWDIN_PERSONAL_TOKEN
project_id_env: CROWDIN_PROJECT_ID
base_path: .
preserve_hierarchy: true
files:
  - source: basiliskLLM.pot
    translation: basilisk/res/locale/%two_letters_code%/LC_MESSAGES/basiliskLLM.po

pull_request_title: "chore: update translations"
pull_request_body: "This PR updates translations file for basiliskLLM"
commit_message: "chore: update translations file from Crowdin for language %language%"
append_commit_message: false
