project_id: 724543
base_path: .
preserve_hierarchy: true
files:
  - source: ./basiliskLLM.pot
    translation: ./res/locale/%two_letters_code%/basiliskLLM.po

pull_request_title: "chore: update translations"
pull_request_body: "This PR updates translations file for basiliskLLM"
commit_message: "chore: update translations file from Crowdin for language %language%"
append_commit_message: false
