name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    steps:
      - name: install wxpython build requirements
        run: |
          sudo apt update
          sudo apt-get install libgtk-3-dev libglew-dev
      - name: Checkout code
        uses: actions/checkout@v5
      - name: setup uv
        uses: astral-sh/setup-uv@v6
      - name: install wxpython 4.2.3
        run: |
          uv venv
          uv pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04/wxpython-4.2.3-cp312-cp312-linux_x86_64.whl
      - name: install dev dependencies
        run: uv sync --frozen --compile --dev
      - name: install pre-commit hook
        run: |
          uv run pre-commit install
          uv run pre-commit install-hooks
