name: "Generate POT file"
on:
  workflow_call:

jobs:
  generate_pot:
    runs-on: windows-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install poetry
        uses: abatilo/actions-poetry@v3
      - name: cache virtualenv
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: ${{ runner.os }}_x64_poetry_${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}_${{ matrix.arch }}_poetry_

      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: build POT file
        run: poetry run python setup.py extract_messages
      - name: upload POT file
        uses: actions/upload-artifact@v4
        with:
          name: basiliskLLM.pot
          path: basiliskLLM.pot
          if-no-files-found: error
          retention-days: 30

  upload_on_crowdin:
    runs-on: ubuntu-latest
    needs: [generate_pot]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: download translations template artifact
        uses: actions/download-artifact@v4
        with:
          pattern: basiliskLLM.pot
      - name: upload on crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
