name: "create release"
on:
  push:
    tags:
      - v*
permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          draft: true
          prerelease: ${{ contains(github.ref_name, 'a')  || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc') }}
